### ISSUE TITLE
Data functions should all work sensibly on h5py datasets

### ISSUE THREAD

**Issue by cmeyer** [nion-software/niondata#2]
'reshape', for instance

Add tests.

**Comment by Brow71189** [comment]
The current implentation prenvents us from processing "large_format" data in many cases. One specific issue reported by ND via email ("Multi-D integrate of shifted will not fourier transform"). The problem is that the Multi-D processing functions create "large_format" data items. ``Core.function_fft`` uses ``ndarray.copy()``  to copy the incoming data, but this fails for h5py datasets because they don't have a ``copy()`` method.
